### ISSUE TITLE
May I add a page linking to the TopasOpt docs?

### ISSUE THREAD

**Issue by bwheelz36** [topasmc/topas-docs#48]
Would like to have a section on 'optimisation', probably placed after outcome modelling.
this would just have a quick TopasOpt description and link to our docs

https://acrf-image-x-institute.github.io/TopasOpt/

Cheers
Brendan

**Comment by jiperl** [comment]
Yes. That would be great.

Of note: there is a problem currently with rebuilding our docs,
Something has changed in the packages of the underlying ReadTheDocs server
such that our doc build is failing. It's on my list to study this week, but for now,
though you are welcome to add the new section, you won't be able to see it in a final public build.
